### ISSUE TITLE
Declarative Resource Manifests

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5802]
This would particularly cool for theme developers so that they don't have to write a C# class to implement a resource manifest provider. Instead, all they need is a resource manifest XML file like this:

```XML
<ResourceManifests>
 <Manifest Name="MyResourceManifest" FeatureId="MyFeatureNameToBindTo">
  <Resources>
   <Script Name="MyScript" Url="myscript.min.js" UrlDebug="myscript.js" Dependencies="jQuery" />
   <Style Name="MyStyle" Url="mystyle.min.css" UrlDebug="mystyle.css" />
  </Resources>
 </Manifest>
</ResourceManifests>
```

Themers can then take advantage of `Script.Require` and have dependencies automatically rendered.
The code is already written and is donated by Bede Gaming. It even has some matching API support so that you could for example group resources for a particular device (Mobile or Desktop). For example:

```XML
<ResourceManifests>
	<Manifest MatchProviderType="BedeGaming.DeviceTypeDetectionMatchProvider, BedeGaming">
		<Resources>
			<Script Name="MyCommonScript" Url="MyCommonScript.js" />
			<Group Match="Desktop">
				<Script Name="MyScript" Url="MyScript.Desktop.js" />
			</Group>
			<Group Match="Mobile">
				<Script Name="MyScript" Url="MyScript.Mobile.js" />
			</Group>
		</Resources>
	</Manifest>
</ResourceManifests>
```XML

**Comment by PaulDevenney** [comment]
+1, We're using this currently to separate our our site creating teams from our Orchard engineering team (our themes are in a separate repo to our customised Orchard solution).

**Comment by bleroy** [comment]
More configuration? In a separate file? In XML? Why not put it in the existing manifest, under features?

**Comment by bleroy** [comment]
Also, maybe limit it to simple cases, that don't require inventing a DSL. If you need more complex things (like the groups above), just write it as code, which is better at expressing logic.

**Comment by sfmskywalker** [comment]
Interesting. So that would look something like this:

```
Resources:
    MyScript:
        Type: Script
        Url: MyScript.min.js
        UrlDebug: MyScript.js
    MyStyle:
        Type: Style
        Url: MyStyle.css
        UrlDebug: MyStyle.min.css
```

Or the resource type could even be inferred from the file extension:

```
Resources:
    MyScript:
        Url: MyScript.min.js
        UrlDebug: MyScript.js
    MyStyle:
        Url: MyStyle.css
        UrlDebug: MyStyle.min.css
```
