### ISSUE TITLE
Group Snippet Fields under configurable tabs

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6796]
Currently, all snippet fields are by default grouped under the "Fields" tab. However, when a snippet contains many fields, it would be useful to be able to group them separately.

This could be done by specifying an optional **tab** name as a field within the snippet manifest, e.g.

```yaml
Fields:
-
 Name: Field1
 Type: Text 
 DisplayName: Field 1
 Tab: My Tab
```
